#!/usr/bin/env bash
#
# install_local.sh - Safe LOCAL setup for VORTEX Agent on a dev machine.
#
# Unlike install/install.sh (a root VPS provisioning script that installs
# systemd services, Caddy, ufw and overwrites your Hermes config), this script:
#   - runs as a normal user (no sudo, no root writes)
#   - keeps everything inside the repo (./venv, ./data)
#   - does NOT install systemd units, Caddy, or firewall rules
#   - does NOT touch your existing ~/.hermes config
#   - only creates a venv and installs the backend Python deps
#
# Usage:
#   cd /path/to/vortex-agent
#   ./install/install_local.sh
#   ./venv/bin/python backend/server.py     # then run the server manually
#
set -euo pipefail

# Resolve repo root (parent of this script's dir), regardless of cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

PY="${PYTHON:-python3}"
VENV="$ROOT/venv"
REQ="$ROOT/install/backend_requirements.txt"
HERMES_ENV="${HOME}/.hermes/.env"

echo "==> Repo root: $ROOT"
echo "==> Python:    $($PY --version 2>&1)"

if [ ! -f "$REQ" ]; then
  echo "ERROR: requirements file not found: $REQ" >&2
  exit 1
fi

# 0. Ensure Hermes .env has VORTEX_ADMIN_KEY + API_SERVER_KEY
if [ ! -f "$HERMES_ENV" ]; then
  mkdir -p "$(dirname "$HERMES_ENV")"
  ADMIN_KEY="$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")"
  {
    echo "# Generated by install_local.sh"
    echo "VORTEX_ADMIN_KEY=${ADMIN_KEY}"
    echo "API_SERVER_KEY=${ADMIN_KEY}"
  } > "$HERMES_ENV"
  echo "==> Created $HERMES_ENV with auto-generated key"
elif ! grep -q '^VORTEX_ADMIN_KEY=' "$HERMES_ENV" 2>/dev/null; then
  ADMIN_KEY="$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")"
  {
    echo "# Added by install_local.sh"
    echo "VORTEX_ADMIN_KEY=${ADMIN_KEY}"
  } >> "$HERMES_ENV"
  echo "==> Added VORTEX_ADMIN_KEY to $HERMES_ENV"
fi

# 1. Create venv (respects PEP 668 - no global pip installs).
if [ ! -d "$VENV" ]; then
  echo "==> Creating virtualenv at $VENV"
  "$PY" -m venv "$VENV"
else
  echo "==> Reusing existing virtualenv at $VENV"
fi

# 2. Upgrade pip + install backend deps into the venv only.
echo "==> Installing backend requirements"
"$VENV/bin/pip" install --upgrade pip
"$VENV/bin/pip" install -r "$REQ"

# 3. Ensure runtime data dirs exist (server also does this, harmless to pre-make).
mkdir -p "$ROOT/data/uploads"

echo
# Print login key
ADMIN_KEY="$(grep '^VORTEX_ADMIN_KEY=' "$HERMES_ENV" | head -1 | cut -d= -f2)"
echo "==> Done. Backend deps installed into $VENV"
echo
echo "Login key:  ${ADMIN_KEY}"
echo "Web UI:     http://<this-host>:61318"
echo
echo "Run:  ./run_local.sh start"
