#!/usr/bin/env bash
#
# install.sh — VORTEX Commander installer (VPS or local).
#
# Usage:
#   ./install/install.sh              # interactive — asks VPS or local
#   ./install/install.sh --mode vps   # force VPS mode (needs sudo)
#   ./install/install.sh --mode local # force local mode
#
# VPS mode:   installs Hermes, systemd services, Caddy reverse-proxy, ufw.
# Local mode: creates venv + installs Python deps only.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

PY="${PYTHON:-python3}"
VENV="$ROOT/venv"
REQ="$ROOT/install/backend_requirements.txt"
HERMES_ENV="${HOME}/.hermes/.env"

echo "================================================"
echo "  VORTEX Commander Installer"
echo "================================================"
echo "  Repo root: $ROOT"
echo "  Python:    $($PY --version 2>&1)"
echo

# ---- mode detection --------------------------------------------------------
MODE="${1:-}"
if [ "$MODE" = "--mode" ]; then
  MODE="${2:-}"
fi

if [ "$MODE" != "vps" ] && [ "$MODE" != "local" ]; then
  echo "Select install mode:"
  echo "  1) VPS   — systemd services, Caddy proxy, firewall (needs sudo)"
  echo "  2) Local — venv + Python deps only (no sudo)"
  echo
  read -rp "Enter choice [1/2]: " choice
  case "$choice" in
    1|vps|VPS) MODE="vps" ;;
    2|local|LOCAL) MODE="local" ;;
    *) echo "ERROR: invalid choice"; exit 1 ;;
  esac
fi

echo "==> Mode: $MODE"
echo

# ---- shared: ensure .env has all required vars -----------------------------
_ensure_env() {
  mkdir -p "$(dirname "$HERMES_ENV")"
  ADMIN_KEY="$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")"

  if [ ! -f "$HERMES_ENV" ]; then
    cat > "$HERMES_ENV" <<EOF
# Generated by VORTEX Commander install.sh
VORTEX_ADMIN_KEY=${ADMIN_KEY}
API_SERVER_KEY=${ADMIN_KEY}
API_SERVER_PORT=${API_SERVER_PORT:-61317}
API_SERVER_HOST=${API_SERVER_HOST:-127.0.0.1}
API_SERVER_ENABLED=true
EOF
    echo "==> Created $HERMES_ENV"
  else
    # Add missing vars if upgrading from older install
    for pair in "VORTEX_ADMIN_KEY=${ADMIN_KEY}" "API_SERVER_KEY=${ADMIN_KEY}" "API_SERVER_PORT=${API_SERVER_PORT:-61317}" "API_SERVER_HOST=${API_SERVER_HOST:-127.0.0.1}" "API_SERVER_ENABLED=true"; do
      key="${pair%%=*}"
      if ! grep -q "^${key}=" "$HERMES_ENV" 2>/dev/null; then
        echo "${pair}" >> "$HERMES_ENV"
        echo "==> Added ${pair} to ${HERMES_ENV}"
      fi
    done
  fi

  ADMIN_KEY="$(grep '^VORTEX_ADMIN_KEY=' "$HERMES_ENV" | head -1 | cut -d= -f2)"
}

if [ "$MODE" = "vps" ]; then
  # ---- VPS mode (needs sudo) ------------------------------------------------
  if [ "$(id -u)" -ne 0 ]; then
    echo "VPS mode needs root. Re-running with sudo ..."
    exec sudo "$0" --mode vps
  fi

  set -x
  export DEBIAN_FRONTEND=noninteractive

  apt-get update -y
  apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
  apt install -y python3-venv python3 nodejs npm openssl

  # ---- Hermes Agent ----
  curl -fsSL --retry 200 --retry-delay 61 --retry-all-errors \
    https://hermes-agent.nousresearch.com/install.sh | bash
  export PATH="$HOME/.local/bin:$PATH"
  hermes config set approvals.mode off
  hermes config set browser.provider local
  hermes config set prompt_caching.cache_ttl 1h

  # ---- .env (root) ----
  _ensure_env

  yes | hermes gateway install --system --run-as-user root
  systemctl enable --now hermes-gateway

  # ---- Backend venv + systemd service ----
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install -r "$REQ"

  sed "s|%REPO%|$ROOT|g" "$ROOT/install/systemd/vortex-backend.service" > /etc/systemd/system/vortex-backend.service
  systemctl daemon-reload
  systemctl enable --now vortex-backend.service

  # ---- Firewall ----
  apt install -y ufw
  ufw allow 80
  ufw allow 443
  ufw --force enable

  # ---- Caddy reverse proxy ----
  apt install -y debian-keyring debian-archive-keyring apt-transport-https
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' > /etc/apt/sources.list.d/caddy-stable.list
  apt update -y
  apt install -y caddy

  PUBLIC_IP=$(hostname -I | awk '{print $1}')
  cat > /etc/caddy/Caddyfile <<CADDYEOF
{
	auto_https disable_redirects
	cert_issuer acme { profile shortlived }
}

http://$PUBLIC_IP {
	reverse_proxy 127.0.0.1:61318
}

https://$PUBLIC_IP {
	reverse_proxy 127.0.0.1:61318
}
CADDYEOF

  systemctl restart caddy

  # ---- Hermes tools ----
  hermes tools disable --platform telegram clarify
  hermes tools enable --platform api_server terminal

  echo ""
  echo "================================================"
  echo "  VORTEX Commander installed (VPS mode)!"
  echo ""
  echo "  Web UI:    http://$PUBLIC_IP"
  echo "  Login key: $ADMIN_KEY"
  echo ""
  echo "  Then open Settings -> VORTEX Agents to add agents."
  echo "================================================"

else
  # ---- Local mode (no sudo) ------------------------------------------------
  if [ ! -f "$REQ" ]; then
    echo "ERROR: requirements file not found: $REQ" >&2
    exit 1
  fi

  _ensure_env

  if [ ! -d "$VENV" ]; then
    echo "==> Creating virtualenv at $VENV"
    "$PY" -m venv "$VENV"
  else
    echo "==> Reusing existing virtualenv at $VENV"
  fi

  echo "==> Installing backend requirements"
  "$VENV/bin/pip" install --upgrade pip
  "$VENV/bin/pip" install -r "$REQ"

  mkdir -p "$ROOT/data/uploads"

  echo
  echo "================================================"
  echo "  VORTEX Commander installed (local mode)!"
  echo ""
  echo "  Login key:  ${ADMIN_KEY}"
  echo "  Web UI:     http://<this-host>:61318"
  echo ""
  echo "  Run:  ./run.sh start"
  echo "================================================"
fi
